// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import './component_controllers'

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import CoinSlotSessionTimerController from "./coin_slot_session_timer_controller"
application.register("coin-slot-session-timer", CoinSlotSessionTimerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PasswordVisibilityController from "./password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import SessionTimerController from "./session_timer_controller"
application.register("session-timer", SessionTimerController)

import ToastEventController from "./toast_event_controller"
application.register("toast-event", ToastEventController)
